baseURL = 'https://giava90.github.io/hugo-instructions/'
languageCode = 'en-us'
title = 'Giacomo Vaccario'
theme = 'simplebutnotsimpler'

[menu]
[[menu.main]]
    name = "Instructions"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Email sent"
    url = "/preparation/"
    weight = 2